export const PERMISSIONS = {
  VIEW_PLATFORM_POLICY: "VIEW_PLATFORM_POLICY",
  MANAGE_PLATFORM_POLICY: "MANAGE_PLATFORM_POLICY",
  VIEW_SUBSCRIPTION: "VIEW_SUBSCRIPTION",
  MANAGE_SUBSCRIPTION: "MANAGE_SUBSCRIPTION",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  VIEW_ADMIN_DASHBOARD: "VIEW_ADMIN_DASHBOARD",
  VIEW_SELLER_DASHBOARD: "VIEW_SELLER_DASHBOARD",
  VIEW_CUSTOMER_DASHBOARD: "VIEW_CUSTOMER_DASHBOARD",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  VIEW_ORDERS: "VIEW_ORDERS",
  APPROVE_SELLER: "APPROVE_SELLER",
  MANAGE_USERS: "MANAGE_USERS",
};

export const ROLE_PERMISSIONS = {
  ADMIN: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.VIEW_PLATFORM_POLICY,
    PERMISSIONS.MANAGE_PLATFORM_POLICY,
    PERMISSIONS.VIEW_SUBSCRIPTION,
    PERMISSIONS.MANAGE_SUBSCRIPTION,
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.APPROVE_SELLER,
    PERMISSIONS.MANAGE_USERS,
  ],

  SELLER: [
    PERMISSIONS.VIEW_SELLER_DASHBOARD,
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,
    PERMISSIONS.VIEW_ORDERS,
  ],

  CUSTOMER: [PERMISSIONS.VIEW_CUSTOMER_DASHBOARD],
};
